package mybatis.dao;

import java.util.List;
import mybatis.model.CheckUserRela;
import mybatis.model.CheckUserRelaExample;
import org.apache.ibatis.annotations.Param;

public interface CheckUserRelaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check_user_rela
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int countByExample(CheckUserRelaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check_user_rela
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int deleteByExample(CheckUserRelaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check_user_rela
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int insert(CheckUserRela record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check_user_rela
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int insertSelective(CheckUserRela record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check_user_rela
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	List<CheckUserRela> selectByExample(CheckUserRelaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check_user_rela
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") CheckUserRela record,
			@Param("example") CheckUserRelaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check_user_rela
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByExample(@Param("record") CheckUserRela record,
			@Param("example") CheckUserRelaExample example);
}