package mybatis.dao;

import java.util.List;
import mybatis.model.Check;
import mybatis.model.CheckExample;
import org.apache.ibatis.annotations.Param;

public interface CheckMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int countByExample(CheckExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int deleteByExample(CheckExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int insert(Check record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int insertSelective(Check record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	List<Check> selectByExample(CheckExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	Check selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Check record,
			@Param("example") CheckExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByExample(@Param("record") Check record,
			@Param("example") CheckExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByPrimaryKeySelective(Check record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table check
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByPrimaryKey(Check record);
}