package mybatis.dao;

import java.util.List;
import mybatis.model.Dvr;
import mybatis.model.DvrExample;
import org.apache.ibatis.annotations.Param;

public interface DvrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int countByExample(DvrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int deleteByExample(DvrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int insert(Dvr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int insertSelective(Dvr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	List<Dvr> selectByExample(DvrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	Dvr selectByPrimaryKey(Integer id);
	Dvr selectAllByPrimaryKey(Integer id);
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Dvr record,
			@Param("example") DvrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByExample(@Param("record") Dvr record,
			@Param("example") DvrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByPrimaryKeySelective(Dvr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	int updateByPrimaryKey(Dvr record);
	
	List<Dvr> selectByAll(@Param("searchKey")String searchKey,@Param("zone")String zone,@Param("status")String status,@Param("platform_type")String platformType,@Param("puid")String puid,@Param("band_number")String bandNumber,@Param("type")String type);
}