package mybatis.model;

import java.util.Date;

public class Check {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column check.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column check.cust_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private Integer custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column check.time
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column check.comment
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column check.type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column check.id
	 * @return  the value of check.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column check.id
	 * @param id  the value for check.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column check.cust_id
	 * @return  the value of check.cust_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Integer getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column check.cust_id
	 * @param custId  the value for check.cust_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column check.time
	 * @return  the value of check.time
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column check.time
	 * @param time  the value for check.time
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column check.comment
	 * @return  the value of check.comment
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column check.comment
	 * @param comment  the value for check.comment
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column check.type
	 * @return  the value of check.type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column check.type
	 * @param type  the value for check.type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}
}