package mybatis.model;

public class CheckUserRela {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column check_user_rela.check_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private Integer checkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column check_user_rela.user_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column check_user_rela.check_id
	 * @return  the value of check_user_rela.check_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Integer getCheckId() {
		return checkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column check_user_rela.check_id
	 * @param checkId  the value for check_user_rela.check_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setCheckId(Integer checkId) {
		this.checkId = checkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column check_user_rela.user_id
	 * @return  the value of check_user_rela.user_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column check_user_rela.user_id
	 * @param userId  the value for check_user_rela.user_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
}