package mybatis.model;

public class Cust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.id
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.owner
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.name
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.contact
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.contact_phone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.cust_mgr
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String custMgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.cust_mgr_phone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String custMgrPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.status
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.zone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.lat
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.lng
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.address
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust.type
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.id
     *
     * @return the value of cust.id
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.id
     *
     * @param id the value for cust.id
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.owner
     *
     * @return the value of cust.owner
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.owner
     *
     * @param owner the value for cust.owner
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.name
     *
     * @return the value of cust.name
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.name
     *
     * @param name the value for cust.name
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.contact
     *
     * @return the value of cust.contact
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.contact
     *
     * @param contact the value for cust.contact
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.contact_phone
     *
     * @return the value of cust.contact_phone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.contact_phone
     *
     * @param contactPhone the value for cust.contact_phone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.cust_mgr
     *
     * @return the value of cust.cust_mgr
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getCustMgr() {
        return custMgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.cust_mgr
     *
     * @param custMgr the value for cust.cust_mgr
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setCustMgr(String custMgr) {
        this.custMgr = custMgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.cust_mgr_phone
     *
     * @return the value of cust.cust_mgr_phone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getCustMgrPhone() {
        return custMgrPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.cust_mgr_phone
     *
     * @param custMgrPhone the value for cust.cust_mgr_phone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setCustMgrPhone(String custMgrPhone) {
        this.custMgrPhone = custMgrPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.status
     *
     * @return the value of cust.status
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.status
     *
     * @param status the value for cust.status
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.zone
     *
     * @return the value of cust.zone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.zone
     *
     * @param zone the value for cust.zone
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.lat
     *
     * @return the value of cust.lat
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.lat
     *
     * @param lat the value for cust.lat
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.lng
     *
     * @return the value of cust.lng
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.lng
     *
     * @param lng the value for cust.lng
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.address
     *
     * @return the value of cust.address
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.address
     *
     * @param address the value for cust.address
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust.type
     *
     * @return the value of cust.type
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust.type
     *
     * @param type the value for cust.type
     *
     * @mbggenerated Thu Jun 25 09:38:55 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }
}