package mybatis.model;

public class Dvr {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.puid
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String puid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.pu_name
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String puName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.cust_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private Integer custId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.platform_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String platformType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.platform_account
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String platformAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.band_number
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String bandNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.band_speed
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String bandSpeed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.band_mode
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String bandMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.band_device
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String bandDevice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.band_port
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String bandPort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.ip
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String dvr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.disk_size
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String diskSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.disk_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String diskType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.dvr_address
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String dvrAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.camera_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String cameraType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.camera_num
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private Integer cameraNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.camera_desc
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String cameraDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.camera_dvr_length
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String cameraDvrLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.property_right
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String propertyRight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dvr.photo_urls
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String photoUrls;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.id
	 * @return  the value of dvr.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.id
	 * @param id  the value for dvr.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.puid
	 * @return  the value of dvr.puid
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPuid() {
		return puid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.puid
	 * @param puid  the value for dvr.puid
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPuid(String puid) {
		this.puid = puid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.pu_name
	 * @return  the value of dvr.pu_name
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPuName() {
		return puName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.pu_name
	 * @param puName  the value for dvr.pu_name
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPuName(String puName) {
		this.puName = puName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.cust_id
	 * @return  the value of dvr.cust_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Integer getCustId() {
		return custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.cust_id
	 * @param custId  the value for dvr.cust_id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.platform_type
	 * @return  the value of dvr.platform_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPlatformType() {
		return platformType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.platform_type
	 * @param platformType  the value for dvr.platform_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPlatformType(String platformType) {
		this.platformType = platformType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.platform_account
	 * @return  the value of dvr.platform_account
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPlatformAccount() {
		return platformAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.platform_account
	 * @param platformAccount  the value for dvr.platform_account
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPlatformAccount(String platformAccount) {
		this.platformAccount = platformAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.band_number
	 * @return  the value of dvr.band_number
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getBandNumber() {
		return bandNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.band_number
	 * @param bandNumber  the value for dvr.band_number
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setBandNumber(String bandNumber) {
		this.bandNumber = bandNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.band_speed
	 * @return  the value of dvr.band_speed
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getBandSpeed() {
		return bandSpeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.band_speed
	 * @param bandSpeed  the value for dvr.band_speed
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setBandSpeed(String bandSpeed) {
		this.bandSpeed = bandSpeed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.band_mode
	 * @return  the value of dvr.band_mode
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getBandMode() {
		return bandMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.band_mode
	 * @param bandMode  the value for dvr.band_mode
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setBandMode(String bandMode) {
		this.bandMode = bandMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.band_device
	 * @return  the value of dvr.band_device
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getBandDevice() {
		return bandDevice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.band_device
	 * @param bandDevice  the value for dvr.band_device
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setBandDevice(String bandDevice) {
		this.bandDevice = bandDevice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.band_port
	 * @return  the value of dvr.band_port
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getBandPort() {
		return bandPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.band_port
	 * @param bandPort  the value for dvr.band_port
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setBandPort(String bandPort) {
		this.bandPort = bandPort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.ip
	 * @return  the value of dvr.ip
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.ip
	 * @param ip  the value for dvr.ip
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.dvr
	 * @return  the value of dvr.dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getDvr() {
		return dvr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.dvr
	 * @param dvr  the value for dvr.dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setDvr(String dvr) {
		this.dvr = dvr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.disk_size
	 * @return  the value of dvr.disk_size
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getDiskSize() {
		return diskSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.disk_size
	 * @param diskSize  the value for dvr.disk_size
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setDiskSize(String diskSize) {
		this.diskSize = diskSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.disk_type
	 * @return  the value of dvr.disk_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getDiskType() {
		return diskType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.disk_type
	 * @param diskType  the value for dvr.disk_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setDiskType(String diskType) {
		this.diskType = diskType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.dvr_address
	 * @return  the value of dvr.dvr_address
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getDvrAddress() {
		return dvrAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.dvr_address
	 * @param dvrAddress  the value for dvr.dvr_address
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setDvrAddress(String dvrAddress) {
		this.dvrAddress = dvrAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.camera_type
	 * @return  the value of dvr.camera_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getCameraType() {
		return cameraType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.camera_type
	 * @param cameraType  the value for dvr.camera_type
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setCameraType(String cameraType) {
		this.cameraType = cameraType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.camera_num
	 * @return  the value of dvr.camera_num
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Integer getCameraNum() {
		return cameraNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.camera_num
	 * @param cameraNum  the value for dvr.camera_num
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setCameraNum(Integer cameraNum) {
		this.cameraNum = cameraNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.camera_desc
	 * @return  the value of dvr.camera_desc
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getCameraDesc() {
		return cameraDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.camera_desc
	 * @param cameraDesc  the value for dvr.camera_desc
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setCameraDesc(String cameraDesc) {
		this.cameraDesc = cameraDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.camera_dvr_length
	 * @return  the value of dvr.camera_dvr_length
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getCameraDvrLength() {
		return cameraDvrLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.camera_dvr_length
	 * @param cameraDvrLength  the value for dvr.camera_dvr_length
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setCameraDvrLength(String cameraDvrLength) {
		this.cameraDvrLength = cameraDvrLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.property_right
	 * @return  the value of dvr.property_right
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPropertyRight() {
		return propertyRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.property_right
	 * @param propertyRight  the value for dvr.property_right
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPropertyRight(String propertyRight) {
		this.propertyRight = propertyRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dvr.photo_urls
	 * @return  the value of dvr.photo_urls
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPhotoUrls() {
		return photoUrls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dvr.photo_urls
	 * @param photoUrls  the value for dvr.photo_urls
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPhotoUrls(String photoUrls) {
		this.photoUrls = photoUrls;
	}

	private Cust cust;
	public Cust getCust() {
		return cust;
	}

	public void setCust(Cust cust) {
		this.cust = cust;
	}
}