package mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class DvrExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public DvrExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPuidIsNull() {
			addCriterion("puid is null");
			return (Criteria) this;
		}

		public Criteria andPuidIsNotNull() {
			addCriterion("puid is not null");
			return (Criteria) this;
		}

		public Criteria andPuidEqualTo(String value) {
			addCriterion("puid =", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidNotEqualTo(String value) {
			addCriterion("puid <>", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidGreaterThan(String value) {
			addCriterion("puid >", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidGreaterThanOrEqualTo(String value) {
			addCriterion("puid >=", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidLessThan(String value) {
			addCriterion("puid <", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidLessThanOrEqualTo(String value) {
			addCriterion("puid <=", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidLike(String value) {
			addCriterion("puid like", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidNotLike(String value) {
			addCriterion("puid not like", value, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidIn(List<String> values) {
			addCriterion("puid in", values, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidNotIn(List<String> values) {
			addCriterion("puid not in", values, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidBetween(String value1, String value2) {
			addCriterion("puid between", value1, value2, "puid");
			return (Criteria) this;
		}

		public Criteria andPuidNotBetween(String value1, String value2) {
			addCriterion("puid not between", value1, value2, "puid");
			return (Criteria) this;
		}

		public Criteria andPuNameIsNull() {
			addCriterion("pu_name is null");
			return (Criteria) this;
		}

		public Criteria andPuNameIsNotNull() {
			addCriterion("pu_name is not null");
			return (Criteria) this;
		}

		public Criteria andPuNameEqualTo(String value) {
			addCriterion("pu_name =", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameNotEqualTo(String value) {
			addCriterion("pu_name <>", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameGreaterThan(String value) {
			addCriterion("pu_name >", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameGreaterThanOrEqualTo(String value) {
			addCriterion("pu_name >=", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameLessThan(String value) {
			addCriterion("pu_name <", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameLessThanOrEqualTo(String value) {
			addCriterion("pu_name <=", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameLike(String value) {
			addCriterion("pu_name like", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameNotLike(String value) {
			addCriterion("pu_name not like", value, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameIn(List<String> values) {
			addCriterion("pu_name in", values, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameNotIn(List<String> values) {
			addCriterion("pu_name not in", values, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameBetween(String value1, String value2) {
			addCriterion("pu_name between", value1, value2, "puName");
			return (Criteria) this;
		}

		public Criteria andPuNameNotBetween(String value1, String value2) {
			addCriterion("pu_name not between", value1, value2, "puName");
			return (Criteria) this;
		}

		public Criteria andCustIdIsNull() {
			addCriterion("cust_id is null");
			return (Criteria) this;
		}

		public Criteria andCustIdIsNotNull() {
			addCriterion("cust_id is not null");
			return (Criteria) this;
		}

		public Criteria andCustIdEqualTo(Integer value) {
			addCriterion("cust_id =", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotEqualTo(Integer value) {
			addCriterion("cust_id <>", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThan(Integer value) {
			addCriterion("cust_id >", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("cust_id >=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThan(Integer value) {
			addCriterion("cust_id <", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdLessThanOrEqualTo(Integer value) {
			addCriterion("cust_id <=", value, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdIn(List<Integer> values) {
			addCriterion("cust_id in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotIn(List<Integer> values) {
			addCriterion("cust_id not in", values, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdBetween(Integer value1, Integer value2) {
			addCriterion("cust_id between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
			addCriterion("cust_id not between", value1, value2, "custId");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNull() {
			addCriterion("platform_type is null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNotNull() {
			addCriterion("platform_type is not null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeEqualTo(String value) {
			addCriterion("platform_type =", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotEqualTo(String value) {
			addCriterion("platform_type <>", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThan(String value) {
			addCriterion("platform_type >", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThanOrEqualTo(String value) {
			addCriterion("platform_type >=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThan(String value) {
			addCriterion("platform_type <", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThanOrEqualTo(String value) {
			addCriterion("platform_type <=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLike(String value) {
			addCriterion("platform_type like", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotLike(String value) {
			addCriterion("platform_type not like", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIn(List<String> values) {
			addCriterion("platform_type in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotIn(List<String> values) {
			addCriterion("platform_type not in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeBetween(String value1, String value2) {
			addCriterion("platform_type between", value1, value2,
					"platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotBetween(String value1, String value2) {
			addCriterion("platform_type not between", value1, value2,
					"platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountIsNull() {
			addCriterion("platform_account is null");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountIsNotNull() {
			addCriterion("platform_account is not null");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountEqualTo(String value) {
			addCriterion("platform_account =", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountNotEqualTo(String value) {
			addCriterion("platform_account <>", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountGreaterThan(String value) {
			addCriterion("platform_account >", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountGreaterThanOrEqualTo(String value) {
			addCriterion("platform_account >=", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountLessThan(String value) {
			addCriterion("platform_account <", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountLessThanOrEqualTo(String value) {
			addCriterion("platform_account <=", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountLike(String value) {
			addCriterion("platform_account like", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountNotLike(String value) {
			addCriterion("platform_account not like", value, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountIn(List<String> values) {
			addCriterion("platform_account in", values, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountNotIn(List<String> values) {
			addCriterion("platform_account not in", values, "platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountBetween(String value1, String value2) {
			addCriterion("platform_account between", value1, value2,
					"platformAccount");
			return (Criteria) this;
		}

		public Criteria andPlatformAccountNotBetween(String value1,
				String value2) {
			addCriterion("platform_account not between", value1, value2,
					"platformAccount");
			return (Criteria) this;
		}

		public Criteria andBandNumberIsNull() {
			addCriterion("band_number is null");
			return (Criteria) this;
		}

		public Criteria andBandNumberIsNotNull() {
			addCriterion("band_number is not null");
			return (Criteria) this;
		}

		public Criteria andBandNumberEqualTo(String value) {
			addCriterion("band_number =", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberNotEqualTo(String value) {
			addCriterion("band_number <>", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberGreaterThan(String value) {
			addCriterion("band_number >", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberGreaterThanOrEqualTo(String value) {
			addCriterion("band_number >=", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberLessThan(String value) {
			addCriterion("band_number <", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberLessThanOrEqualTo(String value) {
			addCriterion("band_number <=", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberLike(String value) {
			addCriterion("band_number like", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberNotLike(String value) {
			addCriterion("band_number not like", value, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberIn(List<String> values) {
			addCriterion("band_number in", values, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberNotIn(List<String> values) {
			addCriterion("band_number not in", values, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberBetween(String value1, String value2) {
			addCriterion("band_number between", value1, value2, "bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandNumberNotBetween(String value1, String value2) {
			addCriterion("band_number not between", value1, value2,
					"bandNumber");
			return (Criteria) this;
		}

		public Criteria andBandSpeedIsNull() {
			addCriterion("band_speed is null");
			return (Criteria) this;
		}

		public Criteria andBandSpeedIsNotNull() {
			addCriterion("band_speed is not null");
			return (Criteria) this;
		}

		public Criteria andBandSpeedEqualTo(String value) {
			addCriterion("band_speed =", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedNotEqualTo(String value) {
			addCriterion("band_speed <>", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedGreaterThan(String value) {
			addCriterion("band_speed >", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedGreaterThanOrEqualTo(String value) {
			addCriterion("band_speed >=", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedLessThan(String value) {
			addCriterion("band_speed <", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedLessThanOrEqualTo(String value) {
			addCriterion("band_speed <=", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedLike(String value) {
			addCriterion("band_speed like", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedNotLike(String value) {
			addCriterion("band_speed not like", value, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedIn(List<String> values) {
			addCriterion("band_speed in", values, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedNotIn(List<String> values) {
			addCriterion("band_speed not in", values, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedBetween(String value1, String value2) {
			addCriterion("band_speed between", value1, value2, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandSpeedNotBetween(String value1, String value2) {
			addCriterion("band_speed not between", value1, value2, "bandSpeed");
			return (Criteria) this;
		}

		public Criteria andBandModeIsNull() {
			addCriterion("band_mode is null");
			return (Criteria) this;
		}

		public Criteria andBandModeIsNotNull() {
			addCriterion("band_mode is not null");
			return (Criteria) this;
		}

		public Criteria andBandModeEqualTo(String value) {
			addCriterion("band_mode =", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeNotEqualTo(String value) {
			addCriterion("band_mode <>", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeGreaterThan(String value) {
			addCriterion("band_mode >", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeGreaterThanOrEqualTo(String value) {
			addCriterion("band_mode >=", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeLessThan(String value) {
			addCriterion("band_mode <", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeLessThanOrEqualTo(String value) {
			addCriterion("band_mode <=", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeLike(String value) {
			addCriterion("band_mode like", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeNotLike(String value) {
			addCriterion("band_mode not like", value, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeIn(List<String> values) {
			addCriterion("band_mode in", values, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeNotIn(List<String> values) {
			addCriterion("band_mode not in", values, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeBetween(String value1, String value2) {
			addCriterion("band_mode between", value1, value2, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandModeNotBetween(String value1, String value2) {
			addCriterion("band_mode not between", value1, value2, "bandMode");
			return (Criteria) this;
		}

		public Criteria andBandDeviceIsNull() {
			addCriterion("band_device is null");
			return (Criteria) this;
		}

		public Criteria andBandDeviceIsNotNull() {
			addCriterion("band_device is not null");
			return (Criteria) this;
		}

		public Criteria andBandDeviceEqualTo(String value) {
			addCriterion("band_device =", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceNotEqualTo(String value) {
			addCriterion("band_device <>", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceGreaterThan(String value) {
			addCriterion("band_device >", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceGreaterThanOrEqualTo(String value) {
			addCriterion("band_device >=", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceLessThan(String value) {
			addCriterion("band_device <", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceLessThanOrEqualTo(String value) {
			addCriterion("band_device <=", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceLike(String value) {
			addCriterion("band_device like", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceNotLike(String value) {
			addCriterion("band_device not like", value, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceIn(List<String> values) {
			addCriterion("band_device in", values, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceNotIn(List<String> values) {
			addCriterion("band_device not in", values, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceBetween(String value1, String value2) {
			addCriterion("band_device between", value1, value2, "bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandDeviceNotBetween(String value1, String value2) {
			addCriterion("band_device not between", value1, value2,
					"bandDevice");
			return (Criteria) this;
		}

		public Criteria andBandPortIsNull() {
			addCriterion("band_port is null");
			return (Criteria) this;
		}

		public Criteria andBandPortIsNotNull() {
			addCriterion("band_port is not null");
			return (Criteria) this;
		}

		public Criteria andBandPortEqualTo(String value) {
			addCriterion("band_port =", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortNotEqualTo(String value) {
			addCriterion("band_port <>", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortGreaterThan(String value) {
			addCriterion("band_port >", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortGreaterThanOrEqualTo(String value) {
			addCriterion("band_port >=", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortLessThan(String value) {
			addCriterion("band_port <", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortLessThanOrEqualTo(String value) {
			addCriterion("band_port <=", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortLike(String value) {
			addCriterion("band_port like", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortNotLike(String value) {
			addCriterion("band_port not like", value, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortIn(List<String> values) {
			addCriterion("band_port in", values, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortNotIn(List<String> values) {
			addCriterion("band_port not in", values, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortBetween(String value1, String value2) {
			addCriterion("band_port between", value1, value2, "bandPort");
			return (Criteria) this;
		}

		public Criteria andBandPortNotBetween(String value1, String value2) {
			addCriterion("band_port not between", value1, value2, "bandPort");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andDvrIsNull() {
			addCriterion("dvr is null");
			return (Criteria) this;
		}

		public Criteria andDvrIsNotNull() {
			addCriterion("dvr is not null");
			return (Criteria) this;
		}

		public Criteria andDvrEqualTo(String value) {
			addCriterion("dvr =", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrNotEqualTo(String value) {
			addCriterion("dvr <>", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrGreaterThan(String value) {
			addCriterion("dvr >", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrGreaterThanOrEqualTo(String value) {
			addCriterion("dvr >=", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrLessThan(String value) {
			addCriterion("dvr <", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrLessThanOrEqualTo(String value) {
			addCriterion("dvr <=", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrLike(String value) {
			addCriterion("dvr like", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrNotLike(String value) {
			addCriterion("dvr not like", value, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrIn(List<String> values) {
			addCriterion("dvr in", values, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrNotIn(List<String> values) {
			addCriterion("dvr not in", values, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrBetween(String value1, String value2) {
			addCriterion("dvr between", value1, value2, "dvr");
			return (Criteria) this;
		}

		public Criteria andDvrNotBetween(String value1, String value2) {
			addCriterion("dvr not between", value1, value2, "dvr");
			return (Criteria) this;
		}

		public Criteria andDiskSizeIsNull() {
			addCriterion("disk_size is null");
			return (Criteria) this;
		}

		public Criteria andDiskSizeIsNotNull() {
			addCriterion("disk_size is not null");
			return (Criteria) this;
		}

		public Criteria andDiskSizeEqualTo(String value) {
			addCriterion("disk_size =", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeNotEqualTo(String value) {
			addCriterion("disk_size <>", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeGreaterThan(String value) {
			addCriterion("disk_size >", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeGreaterThanOrEqualTo(String value) {
			addCriterion("disk_size >=", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeLessThan(String value) {
			addCriterion("disk_size <", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeLessThanOrEqualTo(String value) {
			addCriterion("disk_size <=", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeLike(String value) {
			addCriterion("disk_size like", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeNotLike(String value) {
			addCriterion("disk_size not like", value, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeIn(List<String> values) {
			addCriterion("disk_size in", values, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeNotIn(List<String> values) {
			addCriterion("disk_size not in", values, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeBetween(String value1, String value2) {
			addCriterion("disk_size between", value1, value2, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskSizeNotBetween(String value1, String value2) {
			addCriterion("disk_size not between", value1, value2, "diskSize");
			return (Criteria) this;
		}

		public Criteria andDiskTypeIsNull() {
			addCriterion("disk_type is null");
			return (Criteria) this;
		}

		public Criteria andDiskTypeIsNotNull() {
			addCriterion("disk_type is not null");
			return (Criteria) this;
		}

		public Criteria andDiskTypeEqualTo(String value) {
			addCriterion("disk_type =", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeNotEqualTo(String value) {
			addCriterion("disk_type <>", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeGreaterThan(String value) {
			addCriterion("disk_type >", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeGreaterThanOrEqualTo(String value) {
			addCriterion("disk_type >=", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeLessThan(String value) {
			addCriterion("disk_type <", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeLessThanOrEqualTo(String value) {
			addCriterion("disk_type <=", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeLike(String value) {
			addCriterion("disk_type like", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeNotLike(String value) {
			addCriterion("disk_type not like", value, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeIn(List<String> values) {
			addCriterion("disk_type in", values, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeNotIn(List<String> values) {
			addCriterion("disk_type not in", values, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeBetween(String value1, String value2) {
			addCriterion("disk_type between", value1, value2, "diskType");
			return (Criteria) this;
		}

		public Criteria andDiskTypeNotBetween(String value1, String value2) {
			addCriterion("disk_type not between", value1, value2, "diskType");
			return (Criteria) this;
		}

		public Criteria andDvrAddressIsNull() {
			addCriterion("dvr_address is null");
			return (Criteria) this;
		}

		public Criteria andDvrAddressIsNotNull() {
			addCriterion("dvr_address is not null");
			return (Criteria) this;
		}

		public Criteria andDvrAddressEqualTo(String value) {
			addCriterion("dvr_address =", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressNotEqualTo(String value) {
			addCriterion("dvr_address <>", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressGreaterThan(String value) {
			addCriterion("dvr_address >", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressGreaterThanOrEqualTo(String value) {
			addCriterion("dvr_address >=", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressLessThan(String value) {
			addCriterion("dvr_address <", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressLessThanOrEqualTo(String value) {
			addCriterion("dvr_address <=", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressLike(String value) {
			addCriterion("dvr_address like", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressNotLike(String value) {
			addCriterion("dvr_address not like", value, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressIn(List<String> values) {
			addCriterion("dvr_address in", values, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressNotIn(List<String> values) {
			addCriterion("dvr_address not in", values, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressBetween(String value1, String value2) {
			addCriterion("dvr_address between", value1, value2, "dvrAddress");
			return (Criteria) this;
		}

		public Criteria andDvrAddressNotBetween(String value1, String value2) {
			addCriterion("dvr_address not between", value1, value2,
					"dvrAddress");
			return (Criteria) this;
		}

		public Criteria andCameraTypeIsNull() {
			addCriterion("camera_type is null");
			return (Criteria) this;
		}

		public Criteria andCameraTypeIsNotNull() {
			addCriterion("camera_type is not null");
			return (Criteria) this;
		}

		public Criteria andCameraTypeEqualTo(String value) {
			addCriterion("camera_type =", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeNotEqualTo(String value) {
			addCriterion("camera_type <>", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeGreaterThan(String value) {
			addCriterion("camera_type >", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeGreaterThanOrEqualTo(String value) {
			addCriterion("camera_type >=", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeLessThan(String value) {
			addCriterion("camera_type <", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeLessThanOrEqualTo(String value) {
			addCriterion("camera_type <=", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeLike(String value) {
			addCriterion("camera_type like", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeNotLike(String value) {
			addCriterion("camera_type not like", value, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeIn(List<String> values) {
			addCriterion("camera_type in", values, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeNotIn(List<String> values) {
			addCriterion("camera_type not in", values, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeBetween(String value1, String value2) {
			addCriterion("camera_type between", value1, value2, "cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraTypeNotBetween(String value1, String value2) {
			addCriterion("camera_type not between", value1, value2,
					"cameraType");
			return (Criteria) this;
		}

		public Criteria andCameraNumIsNull() {
			addCriterion("camera_num is null");
			return (Criteria) this;
		}

		public Criteria andCameraNumIsNotNull() {
			addCriterion("camera_num is not null");
			return (Criteria) this;
		}

		public Criteria andCameraNumEqualTo(Integer value) {
			addCriterion("camera_num =", value, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumNotEqualTo(Integer value) {
			addCriterion("camera_num <>", value, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumGreaterThan(Integer value) {
			addCriterion("camera_num >", value, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("camera_num >=", value, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumLessThan(Integer value) {
			addCriterion("camera_num <", value, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumLessThanOrEqualTo(Integer value) {
			addCriterion("camera_num <=", value, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumIn(List<Integer> values) {
			addCriterion("camera_num in", values, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumNotIn(List<Integer> values) {
			addCriterion("camera_num not in", values, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumBetween(Integer value1, Integer value2) {
			addCriterion("camera_num between", value1, value2, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraNumNotBetween(Integer value1, Integer value2) {
			addCriterion("camera_num not between", value1, value2, "cameraNum");
			return (Criteria) this;
		}

		public Criteria andCameraDescIsNull() {
			addCriterion("camera_desc is null");
			return (Criteria) this;
		}

		public Criteria andCameraDescIsNotNull() {
			addCriterion("camera_desc is not null");
			return (Criteria) this;
		}

		public Criteria andCameraDescEqualTo(String value) {
			addCriterion("camera_desc =", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescNotEqualTo(String value) {
			addCriterion("camera_desc <>", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescGreaterThan(String value) {
			addCriterion("camera_desc >", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescGreaterThanOrEqualTo(String value) {
			addCriterion("camera_desc >=", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescLessThan(String value) {
			addCriterion("camera_desc <", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescLessThanOrEqualTo(String value) {
			addCriterion("camera_desc <=", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescLike(String value) {
			addCriterion("camera_desc like", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescNotLike(String value) {
			addCriterion("camera_desc not like", value, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescIn(List<String> values) {
			addCriterion("camera_desc in", values, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescNotIn(List<String> values) {
			addCriterion("camera_desc not in", values, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescBetween(String value1, String value2) {
			addCriterion("camera_desc between", value1, value2, "cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDescNotBetween(String value1, String value2) {
			addCriterion("camera_desc not between", value1, value2,
					"cameraDesc");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthIsNull() {
			addCriterion("camera_dvr_length is null");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthIsNotNull() {
			addCriterion("camera_dvr_length is not null");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthEqualTo(String value) {
			addCriterion("camera_dvr_length =", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthNotEqualTo(String value) {
			addCriterion("camera_dvr_length <>", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthGreaterThan(String value) {
			addCriterion("camera_dvr_length >", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthGreaterThanOrEqualTo(String value) {
			addCriterion("camera_dvr_length >=", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthLessThan(String value) {
			addCriterion("camera_dvr_length <", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthLessThanOrEqualTo(String value) {
			addCriterion("camera_dvr_length <=", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthLike(String value) {
			addCriterion("camera_dvr_length like", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthNotLike(String value) {
			addCriterion("camera_dvr_length not like", value, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthIn(List<String> values) {
			addCriterion("camera_dvr_length in", values, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthNotIn(List<String> values) {
			addCriterion("camera_dvr_length not in", values, "cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthBetween(String value1, String value2) {
			addCriterion("camera_dvr_length between", value1, value2,
					"cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andCameraDvrLengthNotBetween(String value1,
				String value2) {
			addCriterion("camera_dvr_length not between", value1, value2,
					"cameraDvrLength");
			return (Criteria) this;
		}

		public Criteria andPropertyRightIsNull() {
			addCriterion("property_right is null");
			return (Criteria) this;
		}

		public Criteria andPropertyRightIsNotNull() {
			addCriterion("property_right is not null");
			return (Criteria) this;
		}

		public Criteria andPropertyRightEqualTo(String value) {
			addCriterion("property_right =", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightNotEqualTo(String value) {
			addCriterion("property_right <>", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightGreaterThan(String value) {
			addCriterion("property_right >", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightGreaterThanOrEqualTo(String value) {
			addCriterion("property_right >=", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightLessThan(String value) {
			addCriterion("property_right <", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightLessThanOrEqualTo(String value) {
			addCriterion("property_right <=", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightLike(String value) {
			addCriterion("property_right like", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightNotLike(String value) {
			addCriterion("property_right not like", value, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightIn(List<String> values) {
			addCriterion("property_right in", values, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightNotIn(List<String> values) {
			addCriterion("property_right not in", values, "propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightBetween(String value1, String value2) {
			addCriterion("property_right between", value1, value2,
					"propertyRight");
			return (Criteria) this;
		}

		public Criteria andPropertyRightNotBetween(String value1, String value2) {
			addCriterion("property_right not between", value1, value2,
					"propertyRight");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsIsNull() {
			addCriterion("photo_urls is null");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsIsNotNull() {
			addCriterion("photo_urls is not null");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsEqualTo(String value) {
			addCriterion("photo_urls =", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsNotEqualTo(String value) {
			addCriterion("photo_urls <>", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsGreaterThan(String value) {
			addCriterion("photo_urls >", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsGreaterThanOrEqualTo(String value) {
			addCriterion("photo_urls >=", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsLessThan(String value) {
			addCriterion("photo_urls <", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsLessThanOrEqualTo(String value) {
			addCriterion("photo_urls <=", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsLike(String value) {
			addCriterion("photo_urls like", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsNotLike(String value) {
			addCriterion("photo_urls not like", value, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsIn(List<String> values) {
			addCriterion("photo_urls in", values, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsNotIn(List<String> values) {
			addCriterion("photo_urls not in", values, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsBetween(String value1, String value2) {
			addCriterion("photo_urls between", value1, value2, "photoUrls");
			return (Criteria) this;
		}

		public Criteria andPhotoUrlsNotBetween(String value1, String value2) {
			addCriterion("photo_urls not between", value1, value2, "photoUrls");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dvr
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dvr
     *
     * @mbggenerated do_not_delete_during_merge Thu May 28 14:44:43 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}