package mybatis.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.imsi
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String imsi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.auth_code
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	private String authCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.imsi
	 * @return  the value of user.imsi
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getImsi() {
		return imsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.imsi
	 * @param imsi  the value for user.imsi
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.auth_code
	 * @return  the value of user.auth_code
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public String getAuthCode() {
		return authCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.auth_code
	 * @param authCode  the value for user.auth_code
	 * @mbggenerated  Mon Jun 01 17:50:16 CST 2015
	 */
	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}
}